#!/bin/sh

dir=$1
title=$2
path=$3

SOURCE=$HOME/src/iWrapper/build/iWrapper.app

ditto $SOURCE $dir/$title.app
exit 0

perl -i -pe "s%iWrapper%$title%;" $dir/$title.app/Contents/Info.plist
perl -i -pe "s%apple\\.myCocoaApplication%iWrapper.$title%;" \
    $dir/$title.app/Contents/Info.plist
perl -i -pe "s%/home/johnw/bin/backup%$path%;" \
    $dir/$title.app/Contents/Info.plist
